apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: webscada

build:
  artifacts:
    - image: webscada/frontend
      context: .
      docker:
        dockerfile: infrastructure/docker/frontend.Dockerfile
    - image: webscada/backend
      context: .
      docker:
        dockerfile: infrastructure/docker/backend.Dockerfile
    - image: webscada/simulator
      context: .
      docker:
        dockerfile: infrastructure/docker/simulator.Dockerfile
  local:
    push: false
    useBuildkit: true

deploy:
  kubectl:
    manifests:
      - infrastructure/k3s/namespaces/webscada-dev.yaml
      - infrastructure/k3s/manifests/base/postgres-config.yaml
      - infrastructure/k3s/manifests/postgres-deployment.yaml
      - infrastructure/k3s/manifests/redis-deployment.yaml
      - infrastructure/k3s/manifests/base/backend-config.yaml
      - infrastructure/k3s/manifests/base/backend-secrets.yaml
      - infrastructure/k3s/manifests/backend-deployment.yaml
      - infrastructure/k3s/manifests/base/frontend-config.yaml
      - infrastructure/k3s/manifests/frontend-deployment.yaml
      - infrastructure/k3s/manifests/simulator-deployment.yaml
      - infrastructure/k3s/manifests/ingress.yaml
      - infrastructure/k3s/manifests/monitoring/servicemonitor.yaml

portForward:
  - resourceType: service
    resourceName: frontend
    namespace: webscada-dev
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend
    namespace: webscada-dev
    port: 3001
    localPort: 3001
  - resourceType: service
    resourceName: postgres
    namespace: webscada-dev
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: redis
    namespace: webscada-dev
    port: 6379
    localPort: 6379

profiles:
  # Development profile
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: webscada/frontend
          sync:
            manual:
              - src: 'apps/frontend/src/**/*.tsx'
                dest: /app/apps/frontend/src
              - src: 'apps/frontend/src/**/*.ts'
                dest: /app/apps/frontend/src
        - image: webscada/backend
          sync:
            manual:
              - src: 'apps/backend/src/**/*.ts'
                dest: /app/apps/backend/src
    deploy:
      kubectl:
        manifests:
          - infrastructure/k3s/namespaces/webscada-dev.yaml
          - infrastructure/k3s/manifests/base/postgres-config.yaml
          - infrastructure/k3s/manifests/postgres-deployment.yaml
          - infrastructure/k3s/manifests/redis-deployment.yaml
          - infrastructure/k3s/manifests/base/backend-config.yaml
          - infrastructure/k3s/manifests/base/backend-secrets.yaml
          - infrastructure/k3s/manifests/backend-deployment.yaml
          - infrastructure/k3s/manifests/base/frontend-config.yaml
          - infrastructure/k3s/manifests/frontend-deployment.yaml
          - infrastructure/k3s/manifests/simulator-deployment.yaml
          - infrastructure/k3s/manifests/ingress.yaml

  # Production profile with Helm
  - name: prod
    build:
      tagPolicy:
        gitCommit: {}
      local:
        push: true
    deploy:
      helm:
        releases:
          - name: webscada
            chartPath: infrastructure/helm/webscada
            namespace: webscada-dev
            createNamespace: true
            valuesFiles:
              - infrastructure/helm/webscada/values.yaml
            setValues:
              frontend.image.tag: '{{.IMAGE_TAG_webscada_frontend}}'
              backend.image.tag: '{{.IMAGE_TAG_webscada_backend}}'
              simulator.image.tag: '{{.IMAGE_TAG_webscada_simulator}}'
