apiVersion: v1
kind: Namespace
metadata:
  name: webscada-dev
  labels:
    name: webscada-dev
    environment: development
    app: webscada
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: webscada-dev-quota
  namespace: webscada-dev
spec:
  hard:
    # CPU limits - 4 CPUs total
    requests.cpu: "4"
    limits.cpu: "4"

    # Memory limits - 8GB total
    requests.memory: "8Gi"
    limits.memory: "8Gi"

    # Storage limits - 50GB total
    requests.storage: "50Gi"
    persistentvolumeclaims: "10"

    # Object counts
    pods: "50"
    services: "20"
    configmaps: "20"
    secrets: "20"
    services.loadbalancers: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: webscada-dev-limits
  namespace: webscada-dev
spec:
  limits:
    # Pod limits
    - type: Pod
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"

    # Container limits
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "20Gi"
      min:
        storage: "1Gi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webscada-dev-netpol
  namespace: webscada-dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  # Ingress rules
  ingress:
    # Allow from same namespace
    - from:
        - podSelector: {}

    # Allow from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 3001

    # Allow from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090

  # Egress rules
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53

    # Allow to same namespace
    - to:
        - podSelector: {}

    # Allow to internet (for package downloads, API calls, etc.)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80

    # Allow PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432

    # Allow Redis
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379

    # Allow Modbus simulator
    - to:
        - podSelector:
            matchLabels:
              app: simulator
      ports:
        - protocol: TCP
          port: 5020
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webscada-backend
  namespace: webscada-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webscada-frontend
  namespace: webscada-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webscada-dev-role
  namespace: webscada-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webscada-dev-rolebinding
  namespace: webscada-dev
subjects:
  - kind: ServiceAccount
    name: webscada-backend
    namespace: webscada-dev
  - kind: ServiceAccount
    name: webscada-frontend
    namespace: webscada-dev
roleRef:
  kind: Role
  name: webscada-dev-role
  apiGroup: rbac.authorization.k8s.io
